/****** Object:  Table [dbo].[ColumnNameMatch]    Script Date: 12/30/2016 12:07:46 PM ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[ColumnNameMatch](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[SourceColumnName] [varchar](130) NOT NULL,
	[DestinationColumnName] [varchar](130) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY],
 CONSTRAINT [ColumnNameMatches_UniqueMatch] UNIQUE NONCLUSTERED 
(
	[SourceColumnName] ASC,
	[DestinationColumnName] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


